#!/bin/bash
# =============================================================================
# ProveIT 2026 Demo Stack - PostgreSQL Password Initialization Script
# =============================================================================
# Description: This script sets up user passwords from environment variables
# before the main SQL initialization script runs. This ensures passwords are
# never hardcoded in SQL files.
# =============================================================================

set -euo pipefail

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to log messages
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

validate_password() {
    local password="$1"
    local name="$2"

    if [ -z "$password" ]; then
        log_error "Password for $name is empty!"
        return 1
    fi

    if [ ${#password} -lt 12 ]; then
        log_warn "Password for $name is less than 12 characters. Consider using a stronger password."
    fi

    return 0
}

# =============================================================================
# MAIN EXECUTION
# =============================================================================

log_info "Starting PostgreSQL password initialization..."

# Check if running as postgres user (required for initialization)
if [ "$(id -u)" != "$(id -u postgres 2>/dev/null || echo -1)" ] && [ "$(id -u)" != "0" ]; then
    log_error "This script must be run as postgres user or root during container initialization"
    exit 1
fi

# Validate required environment variables
REQUIRED_VARS=(
    "CORE_POSTGRES_CORE_PASSWORD"
    "CORE_POSTGRES_SCADA_PASSWORD"
    "CORE_POSTGRES_MES_FRONTEND_PASSWORD"
    "CORE_POSTGRES_MES_BACKEND_PASSWORD"
)

ALL_VALID=true
for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var:-}" ]; then
        log_error "Environment variable $var is not set!"
        ALL_VALID=false
    else
        # Extract the service name from variable name
        service_name=$(echo "$var" | sed 's/POSTGRES_\(.*\)_PASSWORD/\1/' | tr '[:upper:]' '[:lower:]')
        if ! validate_password "${!var}" "$service_name"; then
            ALL_VALID=false
        fi
    fi
done

if [ "$ALL_VALID" = false ]; then
    log_error "Please set all required environment variables with secure passwords"
    exit 1
fi

# =============================================================================
# CREATE PASSWORD CONFIGURATION FILE
# =============================================================================

# This file will be sourced by the SQL initialization script
cat > /tmp/passwords.sql <<EOF
-- Auto-generated password configuration
-- This file is created by 00-init-passwords.sh from environment variables

-- Set passwords as session variables for use in initialization script
SELECT set_config('app.core_password', '${CORE_POSTGRES_CORE_PASSWORD}', false);
SELECT set_config('app.scada_password', '${CORE_POSTGRES_SCADA_PASSWORD}', false);
SELECT set_config('app.mes_frontend_password', '${CORE_POSTGRES_MES_FRONTEND_PASSWORD}', false);
SELECT set_config('app.mes_backend_password', '${CORE_POSTGRES_MES_BACKEND_PASSWORD}', false);
SELECT set_config('app.monitoring_password', '${CORE_POSTGRES_MONITORING_PASSWORD:-password}', false);
EOF

# Set restrictive permissions on the password file
chmod 600 /tmp/passwords.sql

log_info "Password configuration file created successfully"

# =============================================================================
# PERFORMANCE TUNING BASED ON AVAILABLE RESOURCES
# =============================================================================

# Get available memory in MB
if [ -f /proc/meminfo ]; then
    TOTAL_MEM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
    TOTAL_MEM_MB=$((TOTAL_MEM_KB / 1024))

    # Calculate PostgreSQL memory settings (use 25% of available memory for shared_buffers)
    SHARED_BUFFERS_MB=$((TOTAL_MEM_MB / 4))
    EFFECTIVE_CACHE_SIZE_MB=$((TOTAL_MEM_MB * 3 / 4))

    log_info "Detected ${TOTAL_MEM_MB}MB of available memory"
    log_info "Setting shared_buffers to ${SHARED_BUFFERS_MB}MB"
    log_info "Setting effective_cache_size to ${EFFECTIVE_CACHE_SIZE_MB}MB"

    # Create performance tuning configuration
    cat > /tmp/99-performance.sql <<EOF
-- Auto-generated performance tuning based on available resources
-- Generated by 00-init-passwords.sh

ALTER SYSTEM SET shared_buffers = '${SHARED_BUFFERS_MB}MB';
ALTER SYSTEM SET effective_cache_size = '${EFFECTIVE_CACHE_SIZE_MB}MB';
ALTER SYSTEM SET maintenance_work_mem = '${SHARED_BUFFERS_MB}MB';

-- Ignition-specific optimizations
ALTER SYSTEM SET max_connections = 200;
ALTER SYSTEM SET work_mem = '8MB';
ALTER SYSTEM SET checkpoint_completion_target = 0.9;
ALTER SYSTEM SET wal_buffers = '16MB';
ALTER SYSTEM SET default_statistics_target = 100;
ALTER SYSTEM SET random_page_cost = 1.1;

-- Logging configuration for troubleshooting
ALTER SYSTEM SET log_statement = 'all';
ALTER SYSTEM SET log_duration = on;
ALTER SYSTEM SET log_lock_waits = on;
ALTER SYSTEM SET log_temp_files = 0;

-- Reload configuration
SELECT pg_reload_conf();
EOF

    chmod 644 /tmp/99-performance.sql
fi

# =============================================================================
# CREATE CONNECTION INFO FILE
# =============================================================================

# Create a file with connection information for documentation
cat > /tmp/connection_info.txt <<EOF
=============================================================================
ProveIT PostgreSQL Database Connection Information
=============================================================================

Database Host: postgres (internal Docker network)
Database Port: 5432

Databases and Users:
--------------------
1. Database: ignition_core
   User: ignition_core
   Password: (set via CORE_POSTGRES_CORE_PASSWORD environment variable)
   JDBC URL: jdbc:postgresql://postgres:5432/ignition_core

2. Database: ignition_scada
   User: ignition_scada
   Password: (set via CORE_POSTGRES_SCADA_PASSWORD environment variable)
   JDBC URL: jdbc:postgresql://postgres:5432/ignition_scada

3. Database: ignition_mes_frontend
   User: ignition_mes_frontend
   Password: (set via CORE_POSTGRES_MES_FRONTEND_PASSWORD environment variable)
   JDBC URL: jdbc:postgresql://postgres:5432/ignition_mes_frontend

4. Database: ignition_mes_backend
   User: ignition_mes_backend
   Password: (set via CORE_POSTGRES_MES_BACKEND_PASSWORD environment variable)
   JDBC URL: jdbc:postgresql://postgres:5432/ignition_mes_backend

Monitoring User:
----------------
User: monitoring_readonly
Password: (set via CORE_POSTGRES_MONITORING_PASSWORD environment variable)
Access: Read-only access to all Ignition databases

=============================================================================
EOF

log_info "Connection information file created at /tmp/connection_info.txt"

# =============================================================================
# COMPLETION
# =============================================================================

log_info "PostgreSQL initialization preparation completed successfully"
log_info "The main SQL initialization script will now run..."

# Execute the passwords.sql file to set session variables
if [ -f /tmp/passwords.sql ]; then
    export PGPASSWORD="${CORE_POSTGRES_PASSWORD:-postgres}"
    psql -U "${POSTGRES_USER:-postgres}" -d postgres -f /tmp/passwords.sql
fi